services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1 # pythonのキャッシュを作らないようにする(大量の同期が発生するため)
      - PYTHONUNBUFFERED=1 # Pythonの出力をバッファリングせずリアルタイムで表示させる(エラー追跡のため)
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret_root_pass
      - MYSQL_DATABASE=seaweed_db
      - MYSQL_USER=seaweed_user
      - MYSQL_PASSWORD=seaweed_pass
    volumes:
      - ./docker/db/data:/var/lib/mysql
      # 初期化SQL
      - ./docker/db/query/init.sql:/docker-entrypoint-initdb.d/init.sql